services:
  wordpress:
    image: wordpress:6.9-php8.2-apache
    ports:
      - 127.0.0.1:80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: es4dbuser
      WORDPRESS_DB_PASSWORD: es4dbpass
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html
    networks:
      - wp
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: es4dbuser
      MYSQL_PASSWORD: es4dbpass
      MYSQL_ROOT_PASSWORD: granello
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
      - wp
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3

  dbadmin:
    image: phpmyadmin:5.2.3
    ports:
      - 127.0.0.1:8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

volumes:
  wordpress:
  db:


networks:
  wp:
  db:
