services:
  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend/src:/var/www/html:ro
    networks:
      - frontend
    ports:
      - 80:80

  backend:
    build: ./Backend
    #volumes:
      #- ./Backend/src:/var/www/html:ro
    #per tests
    #ports:
      #- 5050:80
    # Se il container crasha o si ferma, riavvialo sempre, 
    #a meno che non lo fermi io manualmente (docker stop).
    restart: unless-stopped
    # Definisce l'ordine di avvio: il backend dipende dal database
    depends_on:
      database:
      # Docker aspetterà che l'healthcheck del db dica "sono sano"
        condition: service_healthy
    networks:
      - backend
      - frontend
  
  database:
    image: mariadb:12.1.2
    env_file:
      - ./Database/environmentDb/.env
    restart: unless-stopped
    # Docker controlla periodicamente se il database sta funzionando davvero,
    # non solo se il processo è attivo
    healthcheck:
    # Script fornito da MariaDB ('healthcheck.sh') per tentare una connessione e vedere se InnoDB è pronto
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      # Aspetta 15 secondi dall'avvio del container prima di fare il primo controllo
      start_period: 15s
      # Esegui il test ogni 10 secondi
      interval: 10s
      # Se il comando di test ('healthcheck.sh') ci mette più di 5 secondi a rispondere, consideralo fallito
      timeout: 5s
      # Se fallisce 3 volte di fila, Docker segnala che c'è un problema.
      retries: 3
    volumes:
      - dbdata:/var/lib/mysql
      - ./Database/sql/:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend
  
volumes:
  dbdata:

networks:
  backend:
  frontend:
